arhex:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_hinge_front
    pid: {p: 5, i: 0.01, d: 0.1}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_hinge_front
    pid: {p: 5, i: 0.01, d: 0.1}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_hinge_mid
    pid: {p: 5, i: 0.01, d: 0.1}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_hinge_mid
    pid: {p: 5, i: 0.01, d: 0.1}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_hinge_back
    pid: {p: 5, i: 0.01, d: 0.1}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_hinge_back
    pid: {p: 5, i: 0.01, d: 0.1}